### ISSUE TITLE
画像ファイル

### ISSUE THREAD

**Issue by udon1206** [kmyk/algorithm-encyclopedia#101]
アルゴリズムの説明をする際に画像ファイルを用いて説明することもあると思うのですが、画像ファイルを置くフォルダや、ファイルの命名規則はありますか？

**Comment by kmyk** [comment]
まだ画像を使う記事がなく、いまのところ規則は決まっていません。使うとすると、[assets/](https://github.com/kmyk/algorithm-encyclopedia/tree/gh-pages/assets) の下に `img` のようなフォルダを作り、使われるページが分かりやすいように `jhonsn-hoge.png` などという名前で置くのがよいかなと思います。

ただし「どのようにその画像を作成したか」とか「その画像を修整しないといけないとき、どうすればよいか」については、必ずどこか (たとえば Markdown 中に HTML のコメントとして？) に書いておいてください。author の人以外にもそのページを簡単に修整できるようにしておくのは重要です。
