### ISSUE TITLE
align と $$ が上手く機能しない

### ISSUE THREAD

**Issue by noshi91** [kmyk/algorithm-encyclopedia#120]
https://noshi91.github.io/algorithm-encyclopedia/test#noredirect

$$ $$ をどうにかする機能が上手く動いていないように見えます

**Comment by kmyk** [comment]
@noshi91 直ったと思います

**Comment by noshi91** [comment]
直っていないようです。

**Comment by kmyk** [comment]
`$$ ... $$` が `\[ ... \]` に変換される場合もあることが分かりました。勝手に変換するのはいいけどせめて変換先は統一して＞＜
