### ISSUE TITLE
Monotone minima の変種

### ISSUE THREAD

**Issue by noshi91** [kmyk/algorithm-encyclopedia#143]
https://twitter.com/lorent_kyopro/status/1378017376692621312

偶数行で min を計算して interpolate するというアルゴリズムでも (再帰を展開すると) ほとんど同じアルゴリズムが導出できるようです。こちらは SMAWK Algorithm との類似が見られて重要に思うので、追記されるとよいです。

**Comment by kmyk** [comment]
ref #60
