### ISSUE TITLE
Kitamasa 法と高速 Kitamasa 法

### ISSUE THREAD

**Issue by udon1206** [kmyk/algorithm-encyclopedia#149]
> description: Kitamasa 法とは、$k + 1$ 項間の線型漸化式で定まる数列の第 $N$ 項を $O(k^2 \log N)$ で求めるアルゴリズムである。高速 Kitamasa 法とは異なる。

ここでの異なるって表現に少しだけ違和感を抱いたんですけど，勉強したてで認識が間違っていたらあれなんですが，Kitamasa 法と高速 Kitamasa 法って，DFT と FFT みたいな関係という認識で，異なるっていうより高速化かなとおもってるんですけど，違いますかね？(異なるっていうと入力と出力が全然違うものみたいなイメージを抱くんですが，これはぼくの感覚がひょっとしたらおかしいかもです．

あと github の issue 上でみなさんがやってるようなファイルの引用ぽくやるやり方がわからないです．．．

**Comment by kmyk** [comment]
「「Kitamasa 法と高速 Kitamasa 法は同一のアルゴリズムのことを意味する」という言明は偽である」の意味で「Kitamasa 法と高速 Kitamasa 法は異なる」と書きました。
「Kitamasa 法は高速 Kitamasa 法とは無関係のアルゴリズムである」と読めてしまってよくないというのはそうかもしれません。違和感をなくすような書き直しができそうならプルリクをお願いしたいです。

---

`https://github.com/kmyk/algorithm-encyclopedia/blob/d48c73eb9cba330089c0af59d7ac0db46934e976/_algorithms/kitamasa-method.md#L15` のように、ファイルの permalink の URL であって行番号指定付きのものを貼るとできます。ただし Markdown ファイルに対してはこの URL を取得するのはすこし面倒なので、単に引用するので十分だと思います。
ドキュメント: https://docs.github.com/ja/github/managing-your-work-on-github/creating-a-permanent-link-to-a-code-snippet

https://github.com/kmyk/algorithm-encyclopedia/blob/d48c73eb9cba330089c0af59d7ac0db46934e976/_algorithms/kitamasa-method.md#L15

**Comment by noshi91** [comment]
Kitamasa 法: ～。より高速なアルゴリズムに高速 Kitamasa 法がある。
高速 Kitamasa 法: Kitamasa 法を高速化したアルゴリズム。

のようにまとめる手がありそうです。

**Comment by MiSawa** [comment]
これはおそらく僕が悪いんですが、元の Kitamasa 法だと多項式除算の枠組みに直接乗っかってはいないので、オリジナルの問題の定数項の部分に定数/多項式以外の何らかの高速に計算出来る項がある場合にも応用が効くのではという話を @hos-lyric さんがしていました。

ちなみに、DFT と FFT の関係はまた違って、「DFTを求めるアルゴリズムの一つがFFTである」、つまり今回の場合でいうと、線型漸化式の一般項と高速 Kitamasa 法の関係だという認識です。
