### ISSUE TITLE
Lagrange 補間: Lagrange 補間をするという表現について

### ISSUE THREAD

**Issue by noshi91** [kmyk/algorithm-encyclopedia#150]
検索したのですが用例が非常に少ないように思われました。
Lagrange 補間多項式を求めるなどの表現にするのはどうでしょうか？

**Comment by noshi91** [comment]
案 2: 「Lagrange 補間多項式を計算するアルゴリズム」にしてしまう

**Comment by kmyk** [comment]
たしかにほとんど使われていないようです。類似表現として「多項式補間する」もまったく使われていない (競プロerの書いた文章がいくつかだけ見つかる) ことも考えると、避けるべき表現というのは正しそうです。

- "Lagrange 補間する" 10件 (https://www.google.com/search?q=%22Lagrange+%E8%A3%9C%E9%96%93%E3%81%99%E3%82%8B%22)
- "多項式補間をする" 10件 (https://www.google.com/search?q=%22%E5%A4%9A%E9%A0%85%E5%BC%8F%E8%A3%9C%E9%96%93%E3%82%92%E3%81%99%E3%82%8B%22)

案 3: 「Lagrange 補間をするとは、この多項式を求めることである。」の一文は消してしまってもよいかもしれません。

---

ところで、そうなると「Lagrange 補間」が何なのかよく分からなくなってきました。「Lagrange 補間多項式」の型は多項式ですが、では「Lagrange 補間」の型はなにでしょうか？ 以前の私は勝手に「Lagrange 補間する」という動詞の語幹なのだと理解していたのですが、単にアルゴリズム名だと理解すればよい (たとえば「Dijkstra 法をする」が informal なのと同様) ですかね？

**Comment by kmyk** [comment]
いや、Lagrange 補間はアルゴリズムでもないんですよね。なんなのだろう。記事を書くときの本文次第ですが案 2 はわりとありな気がします。
