### ISSUE TITLE
texttt 内で _ が上手く動作しない

### ISSUE THREAD

**Issue by noshi91** [kmyk/algorithm-encyclopedia#161]
https://noshi91.github.io/algorithm-encyclopedia/test#noredirect

疑似コードっぽい感じで説明を書こうとすると texttt 内で _ を使いたいのですが、上手く動作しません。
解決方法はありますか？

**Comment by kmyk** [comment]
ひとまずは `\texttt{a{\char"5f}b}` のように書いてください。

なにが悪くて動作しないのかはよく分かってなくて、後で調べます。

**Comment by kmyk** [comment]
解決方法: `\texttt{a\textunderscore b}` と書いてください。

LaTeX では、texttt 内でアンダースコアを書くには `\texttt{a\_b}` としないといけないようです。KaTeX 上で `\texttt{a_b}` が動かないのは正しい挙動のようです。`\` を付けると Markdown 上では `\texttt{a\\\_b}` になりますが、`\` は難しいので避けたいです。こういうときの汎用の回避手法は `\char` とか `\unicode` なのですが、アンダースコアについては `\textunderscore` があるらしいです。
