### ISSUE TITLE
[アルゴリズム] いわゆる an auxiliary tree なあの木

### ISSUE THREAD

**Issue by kmyk** [kmyk/algorithm-encyclopedia#165]
変な名前で流通しちゃってるのでなんとかしたいという気持ち

**Comment by uwi** [comment]
個人的な興味から軽くルーツを調べてみました。

`虚树`というワードは2016年に中国界隈で使われ始めたようです。2015年以前の記録が単純に見つからない。
https://blog.sengxian.com/algorithms/virtual-tree
https://www.cnblogs.com/zzqsblog/p/5851393.html

一方`auxiliary tree`というワードは、2014年にCodeChefのeditorialに登場しています。とはいえ固有名詞かどうかは曖昧ですね。解法においての補助的なという意味であれば通じてしまいますし。
https://discuss.codechef.com/t/btree-editorial/7647

海外においても、`Virtual Tree`, `Auxiliary Tree`併記したり、私はこう呼ぶみたいなのがあって統一されていない感じですね。 ~海外勢はおかしく思わないのだろうか~

**Comment by uwi** [comment]
そしてSleatorの`Link Cut Tree`の論文でsplay treeたちによって直接できる木構造を`virtual tree`と呼んでいますね。`Link Cut Tree`が表現している有向木を`real tree`として区別しているようです ( https://en.wikipedia.org/wiki/Link/cut_tree )
そしてwikipedia内の説明ではsplay tree1個を`auxiliary tree`と呼んでいる。これもうわかんねえな
