### ISSUE TITLE
Lagrange 補間の計算量のところ

### ISSUE THREAD

**Issue by rsk0315** [kmyk/algorithm-encyclopedia#36]
https://github.com/kmyk/algorithm-encyclopedia/blob/gh-pages/_algorithms/lagrange-interpolation.md

Lagrange 補間に関して、

> $O(N^2)$ あるいは $O(N \log N)$

とあり、おそらく「一般の場合には $O(N)$、$x_i = i$ のような特殊な場合には $O(N \log N)$」ということかと思っているのですが、[これ](https://rsk0315.hatenablog.com/entry/2020/04/05/203210) などの方法で一般の場合でも $O(N (\log N)^2)$ でできるはずなので、そう書く方がいいのかなと思いました。

意図が違ったら困る気がしたので念のため Issue をたてました。

**Comment by kmyk** [comment]
「単純にやると O(N^2) だけど、多項式乗算を頑張るとさらに落ちるらしいよ」ぐらいの意図で書いていました。
Lagrange 補間について最も重要なのは「Lagrange 補間というのは、なにか具体的なひとつのアルゴリズムを指すものではない」ということだと思っていて、それを示す意図で複数の計算量を挙げていました。

計算量について詳しいなら修正を任せたいです。

**Comment by rsk0315** [comment]
えびちゃんの頭がついてないだけだったら申し訳ないんですが、単純にやると Θ(N^3) になりそうな気がしています...？

Lagrange 補間自体が特定のアルゴリズムを指すものではないというのは同意します。
話がまとまったら PR を投げたいと思います。

**Comment by kmyk** [comment]
最も単純にやると O(N^3) なのはそうで、戻す DP みたいにする O(N^2) のことを「単純な」と呼びました。混乱させてしまって申し訳ない。やっぱりつい特定のアルゴリズムを念頭に話をしてしまいがちでよくないですね。

(余力があれば個別のページの作成も検討してみてもらえるとうれしいです)

**Comment by kmyk** [comment]
@rsk0315 これ私の理解が間違ってただけぽいし、プルリク待ってます :pray:
