### ISSUE TITLE
Dijkstraの話: 「完全グラフでは binary heap より Fibonacci heap の方が速い」という言明について

### ISSUE THREAD

**Issue by udon1206** [kmyk/algorithm-encyclopedia#72]
注釈3で

 > AtCoder Regular Contest 064: E - Cosmic Rays (完全グラフ) では binary heap より Fibonacci heap の方が速い。

とありますが，完全グラフでは，愚直にみていくO(|V| ^ 2)が早いことが多い気もしていますし，競技プログラミングにおいてもO(|V| ^ 2)のdijkstraも有用な気がしています．(binary heapと比較なので，話としては別におかしくはないんですが)

実際，現時点の E - Cosmic Rays の最速コード(https://atcoder.jp/contests/arc064/submissions/11186448) はそうなっています． 

あまり本質的な話でもない気がするので，スルーしていただいてもかまいません．

**Comment by kmyk** [comment]
該当部分:

> Fibonacci heap を用いて適切に実装すると計算量が O(\vert E \vert + \vert V \vert \log \vert V \vert)O(∣E∣+∣V∣log∣V∣) に落ちる。これは競技プログラミングの範囲内でもグラフによっては速いことがある34。
>
> https://dic.kimiyuki.net/dijkstra

> rsk0315 の計測によると AtCoder Regular Contest 064: E - Cosmic Rays (完全グラフ) では binary heap より Fibonacci heap の方が速い。(https://twitter.com/rsk0315_h4x/status/1188898280459005954archive.org) ↩
>
> https://dic.kimiyuki.net/dijkstra#fn:rsk0315-fibonacci

**Comment by kmyk** [comment]
link: https://github.com/kmyk/algorithm-encyclopedia/issues/58

**Comment by kmyk** [comment]
これについては @kuretchi (このあたりの記述に詳しそうなレビュワー) と @rsk0315 (計測した人) のふたりに任せていいですか？ お願いします。

**Comment by kuretchi** [comment]
いま記事中で O(|V|²) の Dijkstra 法についてまったく言及がない状態なので，まずはそれを加筆して，その上で該当部分に一言加えるのが良いかなと思っています．

**Comment by kmyk** [comment]
いまさらだけど、次ののしさんの記事を紹介しておくとよかったのではないか

<blockquote class="twitter-tweet" data-partner="tweetdeck"><p lang="ja" dir="ltr"><a href="https://t.co/veQ4kpH53i">https://t.co/veQ4kpH53i</a><br><br>Binary Heap を用いた Dijkstra 法の最悪ケースを作って、Fibonacci Heap による実装と比較しました。「Binary Heap の最悪ケースでは」、V と E がさほど離れていなくても Fibonacci Heap が std::priority_queue より高速になるようです</p>&mdash; 熨斗袋 (@noshi91) <a href="https://twitter.com/noshi91/status/1366338426677596167?ref_src=twsrc%5Etfw">March 1, 2021</a></blockquote>
