### ISSUE TITLE
英語の名称を添える

### ISSUE THREAD

**Issue by amylase** [kmyk/algorithm-encyclopedia#73]
この辞典は日本人向けに日本語で提供されている情報ではありますが、追加の情報が必要だとか Codeforces/ICPC で問題をフィルタする際とかに英語の名称を知っていると便利な局面は多いので英語の名称を見出しの横に添えませんか？
しゃくとり法 (two pointers) のように日本語とかなり違う呼び方をされる場合もあるので。

**Comment by kmyk** [comment]
すでに別名を書く欄は用意してあります。これをもっとちゃんと書いた上で、その中身を見出し一覧のページにも表示するようにするとよさそうです。
https://github.com/kmyk/algorithm-encyclopedia/blob/gh-pages/CONTRIBUTING.md#:~:text=aliases
