### ISSUE TITLE
ご提案: Markdownファイルに掲載されているリンクの自動チェック

### ISSUE THREAD

**Issue by KATO-Hiro** [kmyk/algorithm-encyclopedia#89]
こんばんは。

表題の内容について、ご提案とご相談です。

## リンクの自動チェックを導入する理由

- 掲載されているリンク先が閲覧できることを保証するため
- 上記の内容を担保するために、手動で動作確認行うのは手間がかかるため

### GitHub Action - Markdown link checkを導入

https://github.com/gaurav-nelson/github-action-markdown-link-check
https://github.com/tcort/markdown-link-check

#### リンクのチェック対象と、そのタイミング
  - プルリクエストに含まれる修正内容に対して実行
  - サイト全体に対して定期的に実行
    - 参考: [拙サイト](https://kato-hiro.github.io/AtCoderClans)では、毎日0:30(JST)にチェックしています

#### 該当ディレクトリ・ファイル
  - _algorithms
  - _tenkeis
  - tenkei
  - CONTRIBUTING.md
  - DESIGN.md
  - README.md
  - index.md

#### 対象外のディレクトリ・ファイル(リンクが含まれておらず、チェックの優先度は低いと思われるため)
  - .github/ISSUE_TEMPLATE
  - template.md

## 懸念事項、相談したいこと

- ツールの導入に関するプルリクエストを送る際も、AtCoder〇色以上といった制約はありますでしょうか?

- サイト全体に対するリンクチェックの頻度は、どの程度がふさわしいとお考えでしょうか?
  - 頻度
    - 1日に1回
    - 1週間に1回
    - その他

**Comment by kmyk** [comment]
リンクの自動チェックは必要そうです。ありがとうございます。

ただし、markdown-link-check を使うのには賛成しません。我々の用途にはそぐわないように思います。
リンクが切れたことを検出するだけでは意味がなく、リンク先のページをどこかに保存しておく必要があります。リンクを張るときは常に Internet Archive を併用することを推奨しています。専用のスクリプトを書いて「そのリンクされているページが Internet Archive に保存されており、その保存されたページへのリンクも併記されている」ことまでを確認すべきでしょう。

---

> ツールの導入に関するプルリクエストを送る際も、AtCoder〇色以上といった制約はありますでしょうか?

いいえ。記事を書くときもツールについての提案をするときも、レートについての制約はありません。

> サイト全体に対するリンクチェックの頻度は、どの程度がふさわしいとお考えでしょうか?

「その他」です。「定期的にリンクチェックを実行する」というやり方では不十分です。

**Comment by KATO-Hiro** [comment]
ご丁寧な返信をいただき、ありがとうございます。

> ただし、markdown-link-check を使うのには賛成しません。我々の用途にはそぐわないように思います。
> リンクが切れたことを検出するだけでは意味がなく、リンク先のページをどこかに保存しておく必要があります。リンクを張るときは常に Internet Archive を併用することを推奨しています。専用のスクリプトを書いて「そのリンクされているページが Internet Archive に保存されており、その保存されたページへのリンクも併記されている」ことまでを確認すべきでしょう。

CONTRIBUTING.mdを改めて拝見いたしました。
ご指摘の通りだと思います。


スクリプトを実装する前に、必要だと思われる大まかな処理を列挙しました。
ご意見をいただいても、よろしいでしょうか?

- 単一のMarkdownファイル対する処理、チェック事項
  - ファイル内に含まれているリンクを抽出する
  - リンクがアクセスできるかどうかレスポンスコードで判定
  - Internet Archiveに登録されているか判定
  - Internet Archiveに登録されていなければ追加する(要相談)

- 対象となる全てのMarkdownファイルに対して、上記のチェックを実行する

- GitHub Actionsを利用して自動化する


> いいえ。記事を書くときもツールについての提案をするときも、レートについての制約はありません。

承知いたしました。


> > サイト全体に対するリンクチェックの頻度は、どの程度がふさわしいとお考えでしょうか?
> 
> 「その他」です。「定期的にリンクチェックを実行する」というやり方では不十分です。

代替案を考えました。いかがでしょうか?

- プルリクエストを作成したとき
- gh-pagesブランチにmergeするとき

**Comment by kmyk** [comment]
> スクリプトを実装する前に、必要だと思われる大まかな処理を列挙しました。
> ご意見をいただいても、よろしいでしょうか?
>
> - 単一のMarkdownファイル対する処理、チェック事項
>
>     - ファイル内に含まれているリンクを抽出する
>     - リンクがアクセスできるかどうかレスポンスコードで判定
>     - Internet Archiveに登録されているか判定
>     - Internet Archiveに登録されていなければ追加する(要相談)
> - 対象となる全てのMarkdownファイルに対して、上記のチェックを実行する
>
> - GitHub Actionsを利用して自動化する

「ファイル内に含まれているリンクを抽出する」
それはそうという感じですが、実装方法の議論が必要なはずです。Markdown ファイル中に含まれているリンクを列挙するのはかなり難しい処理であり、丁寧にやろうとすると専用のライブラリが必須です。一方で、依存ライブラリを増やすとそのインストールでつまずく人が増えるという問題もあります。
どうせ PyYAML が要求されていることから、依存ライブラリが少ないライブラリなら追加で要求しても大丈夫なはずで、デファクトな [Python-Markdown/markdown](https://github.com/Python-Markdown/markdown) を使うのがよいでしょう。

「リンクがアクセスできるかどうかレスポンスコードで判定」「Internet Archiveに登録されているか判定」
これはできれば避けたいです。このようなチェックは pre-commit hook の際に実行すべきであり、すべての URL について HTTP リクエストを飛ばすのはうれしくありません。
オプションで有効になるようにしておいて、schedule からの起動であれば追加で HTTP リクエストを飛ばす、というのはよいかもしれません。

「Internet Archiveに登録されていなければ追加する」
これは手動でやってもらうようにしたいです。できるだけ多くの競プロerに Internet Archive への保存方法を覚えてもらって、この辞典への記事を書くとき以外にも適宜保存ができるようになってもらいたいためです。

> > > サイト全体に対するリンクチェックの頻度は、どの程度がふさわしいとお考えでしょうか?
> >
> > 「その他」です。「定期的にリンクチェックを実行する」というやり方では不十分です。
>
> 代替案を考えました。いかがでしょうか?
>
> - プルリクエストを作成したとき
> - gh-pagesブランチにmergeするとき

ローカル実行も忘れないようにしたいです。つまり「GitHub に push したとき」かつ「プルリクエストを作成したとき」かつ「記事を執筆中の競プロerが手動で実行する」がよいと思います。

---

なんとなく [scripts/lint.py](https://github.com/kmyk/algorithm-encyclopedia/blob/gh-pages/scripts/lint.py) の存在に気づいてもらえてなさそうなので、念の為これに言及しておきます。詳しくは [CONTRIBUTING.md#ローカルでのテストの実行](https://github.com/kmyk/algorithm-encyclopedia/blob/gh-pages/CONTRIBUTING.md#%E3%83%AD%E3%83%BC%E3%82%AB%E3%83%AB%E3%81%A7%E3%81%AE%E3%83%86%E3%82%B9%E3%83%88%E3%81%AE%E5%AE%9F%E8%A1%8C) も読んでください。

@KATO-Hiro リンクの自動チェックなどの「記事を書くことを助けるためのツール」をどう改善すればよいかについては、やはり「記事を実際に書いたことのある人」でないとよく分からないと思います。リンクの自動チェックはかなり面倒な機能だと思いますし、スクリプトの実装の前に、ひとまず自分でなにかひとつ記事を作成してみてもよいかもしれません。記事の作成にもレートの制約はありませんし、もし仮に間違ったことを書いたとしてもレッドコーダーたちがやさしくきっちり指摘してくれるので安心です。

**Comment by KATO-Hiro** [comment]
> なんとなく [scripts/lint.py](https://github.com/kmyk/algorithm-encyclopedia/blob/gh-pages/scripts/lint.py) の存在に気づいてもらえてなさそうなので、念の為これに言及しておきます。詳しくは [CONTRIBUTING.md#ローカルでのテストの実行](https://github.com/kmyk/algorithm-encyclopedia/blob/gh-pages/CONTRIBUTING.md#%E3%83%AD%E3%83%BC%E3%82%AB%E3%83%AB%E3%81%A7%E3%81%AE%E3%83%86%E3%82%B9%E3%83%88%E3%81%AE%E5%AE%9F%E8%A1%8C) も読んでください。

> @KATO-Hiro リンクの自動チェックなどの「記事を書くことを助けるためのツール」をどう改善すればよいかについては、やはり「記事を実際に書いたことのある人」でないとよく分からないと思います。リンクの自動チェックはかなり面倒な機能だと思いますし、スクリプトの実装の前に、ひとまず自分でなにかひとつ記事を作成してみてもよいかもしれません。記事の作成にもレートの制約はありませんし、もし仮に間違ったことを書いたとしてもレッドコーダーたちがやさしくきっちり指摘してくれるので安心です。


お時間を割いて、スクリプトの実装に必要な検討項目についてご教示いただき、ありがとうございます。

今の私の理解度からすると、ご提示いただいたドキュメントやコードの読解、記事の加筆・修正で貢献できそうな部分を探すことを優先したほうがよいと判断しました。

このような貴重な機会をいただき、ありがとうございます。
