### ISSUE TITLE
author でない人がページに変更を加えるときの手続き、それの明文化

### ISSUE THREAD

**Issue by noshi91** [kmyk/algorithm-encyclopedia#91]
ページの内容について問題があると、名前が載っている author や reviewer の印象も下げてしまう可能性があります。したがって、既に存在するページに author でも reviewer でもない人が手を加えるときに、理想的には双方に確認を取りたいです。この手続きを出来る限り厳密に書き、明文化したいです。それは名前を載せるときに保証されるべき権利と考えるからです。

第三者の修正に対して名前をどうするかの選択を author にしてもらうというのもありかもしれないと考えています。例えば「誤字や脱字を除く修正が入ったら直ちに名前を外す」「GitHub 上でメンションを行い、2 日間反応が無かったら merge する (当然 admin チェックは入る)」などを選んでもらうということです。

**Comment by noshi91** [comment]
前述の案は実現可能性をあまり考えていないのですが、ページにコメントで入れてもらうとか pull request の時に書いてもらうとかで運用できるのだろうか。

ページが増える前に手を打ちたいので、意見を募集しています。 (特に @kmyk)

**Comment by kmyk** [comment]
修正に対する態度の選択を都度してもらうのは実現可能です。たとえば、Markdown ファイル中にメタデータの一部として書くようにして、それが書かれてないと :x: が付くようにすることができます。

**Comment by kmyk** [comment]
修正に対する態度としては、以下のどちらかだけを考えればよいはずです。

1. 「まずは GitHub 上でリプライをしてほしい。返事がない場合は、誤字や脱字などならよいが、それ以上の変更があるなら名前を削除してほしい。」
2.  「まずは GitHub 上でリプライをしてほしい。返事がない場合は、とりあえず名前は残しておいてほしい。」

これらに対して、

1. それぞれの author / reviewer にその都度どちらか選択してもらう
2. サイト全体でどちらを採用するかを決めてしまう

のどちらかという選択肢があります。

あるいは、選択肢 3. として、もっと細かく author / reviewer の表示をするという選択肢もあります。たとえば「2021-02-02 の author / reviewers は A / B, C で、その後 2021-03-01 の修正の author / reviewers は D / A, C である」のような表示をしてしまえば、もっとも正確に貢献者を伝えられるはずです。

---

選択肢 1 と選択肢 3 の手間は変わらないはず (どちらも書くことは増えてすこし手間) です。個人的には (諸々の明文化はした上で) 選択肢 3 がよい気がします。

**Comment by noshi91** [comment]
一定以上の (これも基準がないと面倒そうですが) 貢献があった人は全員 author reviewer に入れて、細かい貢献の場所は view history から確認してもらうというのと違いはありますか？ 日付を入れてもどこを書いたかはわからないので、結局 history を見るしかないと思っています。

**Comment by kmyk** [comment]
> 一定以上の (これも基準がないと面倒そうですが) 貢献があった人は全員 author reviewer に入れて、細かい貢献の場所は view history から確認してもらうというのと違いはありますか？

authors reviewers が全員で同時に作業したわけではない (ある author あるいは reviewer が存在し、ページ中に文章のある部分が存在し、その人はその部分に関与していない) ことが明確になる、というのが違いです。我々が防ぎたいのは authors reviewers についての不利益な勘違い (すべての authors とすべての reviewers が、ページ中の文章のすべての部分に対して、責任を持っている) なわけですが、選択肢 3 はこの勘違いを防ぐことのできる選択肢 (のうちのひとつ) だと考えています。

どのような手法であっても結局は "View History" を見るのがもっとも正確であるというのは正しいです。しかしほとんどすべての読者は history を確認しようとはしないでしょう。authors や reviewers の表示は「そのような多くの読者に対しても分かりやすく貢献者を伝える」ためにあるはずです。

**Comment by noshi91** [comment]
今の表示形態を変えて、
author hoge1 reviewer fuga1 yyyy:mm:dd ページの作成
author hoge2 reviewer fuga2 yyyy:mm:dd 具体的なアルゴリズム内容の執筆
みたいなのをページ最下部に並べるイメージですか？

**Comment by kmyk** [comment]
はい。そのようなものをイメージしています。
いわゆる [CHANGELOG](https://keepachangelog.com/) のとても簡易なものになるはずです。

**Comment by kmyk** [comment]
いまさらだけど、すでに authors / reviewers に名前が入ってる人たちに ping しておく: @jupiro @kuretchi @minaminao

**Comment by noshi91** [comment]
賛成です。

**Comment by kmyk** [comment]
明文化と表示方法の改善について、近いうちにやります。
